apiVersion: v1
kind: Pod
metadata:
  name: getting-started
spec:
  containers:
    - name: getting-started
      image: skaffold-example
      resources:
        limits:
          memory: 200Mi
          cpu: 200m
